server:
  contextPath: /api/v1
  port: 8080

spring:
  application.name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/database_name
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
